const VITE_START_HOUR = window.VITE_START_HOUR || '6';
const VITE_NUMBER_OF_HOURS = window.VITE_ADDITIONAL_NEXT_DAY_HOURS || '18';
const VITE_API_DOMAIN = window.VITE_API_DOMAIN || 'link.com';
const VITE_VAM_INTERVAL = window.VITE_VAM_INTERVAL || '10000';
const VITE_CAM_INTERVAL = window.VITE_CAM_INTERVAL || '10000';
const VITE_LIVE_SCROLLING_SPEED = window.VITE_LIVE_SCROLLING_SPEED || '2';

export {
  VITE_START_HOUR,
  VITE_NUMBER_OF_HOURS,
  VITE_API_DOMAIN,
  VITE_VAM_INTERVAL,
  VITE_CAM_INTERVAL,
  VITE_LIVE_SCROLLING_SPEED,
};
